### ISSUE TITLE
Which version of flutter you use?

### ISSUE THREAD

**Issue by victoire-hergan** [prijindal/habiticapp#1]
Hello,

Thank you for your great work, I want to progress with flutter and habitica, it's perfect, thank you!

Which version of flutter you use?

I am using Flutter 1.5.4-hotfix.2 and Dart 2.3.0

I tried to install locally, it works, but tasks are not visible, with this in console log:

```
I/flutter (18567): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (18567): The following assertion was thrown during performLayout():
I/flutter (18567): Trailing widget consumes entire tile width. Please use a sized widget.
I/flutter (18567): 'package:flutter/src/material/list_tile.dart': Failed assertion: line 1338 pos 7: 'tileWidth !=
I/flutter (18567): trailingSize.width'
I/flutter (18567): 
I/flutter (18567): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (18567): more information in this error message to help you determine and fix the underlying cause.
I/flutter (18567): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (18567):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (18567): 
I/flutter (18567): When the exception was thrown, this was the stack:
I/flutter (18567): #2      _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:1338:7)
I/flutter (18567): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #4      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (18567): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #15     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
I/flutter (18567): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #17     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (18567): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #23     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:165:27)
I/flutter (18567): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #25     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (18567): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #27     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
I/flutter (18567): #28     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1651:12)
I/flutter (18567): #29     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1614:20)
I/flutter (18567): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #53     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:200:18)
I/flutter (18567): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #55     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
I/flutter (18567): #56     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
I/flutter (18567): #57     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
I/flutter (18567): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #77     RenderSliverFillRemaining.performLayout (package:flutter/src/rendering/sliver_fill.dart:122:13)
I/flutter (18567): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #79     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
I/flutter (18567): #80     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
I/flutter (18567): #81     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
I/flutter (18567): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #83     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #85     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #87     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #89     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #91     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #93     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #95     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #97     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #98     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #99     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #100    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #101    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (18567): #102    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #103    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (18567): #104    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:431:7)
I/flutter (18567): #105    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (18567): #106    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (18567): #107    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #108    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #109    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #110    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
D/libGLESv2(18567): STS_GLApi : DTS, ODTC are not allowed for Package : com.prijindal.habitter
I/zygote64(18567): Do partial code cache collection, code=30KB, data=18KB
I/zygote64(18567): After code cache collection, code=24KB, data=17KB
I/zygote64(18567): Increasing code cache capacity to 128KB
I/flutter (18567): #111    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
I/flutter (18567): #112    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #113    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #114    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #115    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #116    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #117    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #118    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #119    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #120    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #121    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #122    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #123    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #124    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #125    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #126    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #127    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #128    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3015:13)
I/flutter (18567): #129    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #130    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (18567): #131    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #132    __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #133    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #134    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #135    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #136    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #137    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #138    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #139    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #140    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #141    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #142    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (18567): #143    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (18567): #144    RenderView.performLayout (package:flutter/src/rendering/view.dart:151:13)
I/flutter (18567): #145    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
I/flutter (18567): #146    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter (18567): #147    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:347:19)
I/flutter (18567): #148    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (18567): #149    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (18567): #150    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (18567): #151    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (18567): #152    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (18567): #156    _invoke (dart:ui/hooks.dart:219:10)
I/flutter (18567): #157    _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (18567): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (18567): 
I/flutter (18567): The following RenderObject was being processed when the exception was fired:
I/flutter (18567):   _RenderListTile#f93a2 relayoutBoundary=up12 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):   creator: _ListTile ← MediaQuery ← Padding ← SafeArea ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (18567):   RawGestureDetector ← GestureDetector ← InkWell ← ListTile ← DefaultTextStyle ← ⋯
I/flutter (18567):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (18567):   constraints: BoxConstraints(w=328.0, 0.0<=h<=Infinity)
I/flutter (18567):   size: MISSING
I/flutter (18567): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (18567):   RenderFlex#fa807 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):     RenderSemanticsGestureHandler#a536b NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):       RenderPointerListener#1be86 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):         RenderSemanticsAnnotations#fe8be NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):           RenderConstrainedBox#f8c7a NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):     RenderConstrainedBox#af908 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):       RenderFlex#9317a NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):         RenderPadding#b82a8 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):           RenderFlex#6c38d NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):         RenderFlex#d62e5 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):           RenderPadding#d7d38 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):     RenderSemanticsGestureHandler#5983c NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):       RenderPointerListener#0c56e NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):         RenderSemanticsAnnotations#ae427 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):           RenderConstrainedBox#29e62 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (18567):   RenderClipRect#05b24 relayoutBoundary=up13 NEEDS-PAINT
I/flutter (18567):     RenderAnimatedSize#9d4bf relayoutBoundary=up14 NEEDS-PAINT
I/flutter (18567):       RenderStack#17e2e relayoutBoundary=up15 NEEDS-PAINT
I/flutter (18567):         RenderExcludeSemantics#a0500 relayoutBoundary=up16 NEEDS-PAINT
I/flutter (18567):           RenderAnimatedOpacity#5df46 relayoutBoundary=up17 NEEDS-PAINT
I/flutter (18567):         RenderExcludeSemantics#935b6 relayoutBoundary=up16 NEEDS-PAINT
I/flutter (18567):           RenderAnimatedOpacity#28ec6 relayoutBoundary=up17 NEEDS-PAINT
I/flutter (18567): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (18567): Another exception was thrown: RenderBox was not laid out: _RenderListTile#f93a2 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (18567): Another exception was thrown: RenderBox was not laid out: RenderPadding#2bd03 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (18567): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#42f8d relayoutBoundary=up10 NEEDS-PAINT
I/flutter (18567): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#100e9 relayoutBoundary=up9 NEEDS-PAINT
I/flutter (18567): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#ac25e relayoutBoundary=up8 NEEDS-PAINT
I/flutter (18567): Another exception was thrown: RenderBox was not laid out: _RenderInkFeatures#2cc55 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (18567): Another exception was thrown: RenderBox was not laid out: RenderPhysicalModel#ad501 relayoutBoundary=up6 NEEDS-PAINT
I/flutter (18567): Another exception was thrown: RenderBox was not laid out: RenderPadding#50c9e relayoutBoundary=up5 NEEDS-PAINT
I/flutter (18567): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#37717 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (18567): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 470 pos 12: 'child.hasSize': is not true.
V/InputMethodManager(18567): Starting input: tba=android.view.inputmethod.EditorInfo@632f004 nm : com.prijindal.habitter ic=null
I/InputMethodManager(18567): startInputInner - mService.startInputOrWindowGainedFocus
D/SurfaceView(18567): BG show() Surface(name=Background for - SurfaceView - com.prijindal.habitter/com.prijindal.habitter.MainActivity@d366e79@0) io.flutter.view.FlutterView{d366e79 VFE...... .F...... 0,0-1080,1920}
D/SurfaceView(18567): surfaceDestroyed 1 #1 io.flutter.view.FlutterView{d366e79 VFE...... .F...... 0,0-1080,1920}
D/ViewRootImpl@e72b1e6[MainActivity](18567): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 72 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl@e72b1e6[MainActivity](18567): MSG_WINDOW_FOCUS_CHANGED 0
D/ViewRootImpl@e72b1e6[MainActivity](18567): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
D/SurfaceView(18567): BG show() Surface(name=Background for - SurfaceView - com.prijindal.habitter/com.prijindal.habitter.MainActivity@d366e79@0) io.flutter.view.FlutterView{d366e79 VFE...... .F....I. 0,0-1080,1920}
D/OpenGLRenderer(18567): eglDestroySurface = 0x78ba7ffb00
D/ViewRootImpl@e72b1e6[MainActivity](18567): Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x5 surface={valid=false 0} changed=true
```

**Comment by prijindal** [comment]
It's been a while since i have worked on it and i was using an older version of flutter, probably something in v1.2 or maybe 1.1.
Anyways the problem seems to be with some changes to internal rendering of listtile by flutter. I will take a look at it once i get some free time
